<?php
/**
 * @file
 * All image styles for the BADCamp site, exported to code.
 */

/**
 * Implements hook_image_default_styles().
 * Provide custom image styles for the NEW CPR site. 
 */
function badcamp_images_image_default_styles() {
  $styles = array();

  $styles['highlight'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop', 
        'data' => array(
          'width' => 550,
          'height' => 188,
          'upscale' => 1,
        ),
        'weight' => 0,
      ),
    ),
  );
  $styles['headshot'] = array(
    'effects' => array(
      array(
        'name' => 'image_scale_and_crop', 
        'data' => array(
          'width' => 175,
          'height' => 175,
          'upscale' => 0,
        ),
        'weight' => 0,
      ),
    ),
  );

  $styles['sponsor_large']['effects'] = array(
    0 => array(
      'label' => 'Scale',
      'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
      'effect callback' => 'image_scale_effect',
      'dimensions callback' => 'image_scale_dimensions',
      'form callback' => 'image_scale_form',
      'summary theme' => 'image_scale_summary',
      'module' => 'image',
      'name' => 'image_scale',
      'data' => array(
        'width' => '255',
        'height' => '255',
        'upscale' => 0,
      ),
      'weight' => '1',
    ),
    1 => array(
      'label' => 'Underlay (background)',
      'help' => 'Choose the file image you wish to use as an background, and position the processed image on it.',
      'effect callback' => 'canvasactions_canvas2file_image',
      'form callback' => 'canvasactions_canvas2file_form',
      'module' => 'imagecache_canvasactions',
      'name' => 'canvasactions_canvas2file',
      'data' => array(
        'xpos' => 'center',
        'ypos' => 'center',
        'alpha' => '100',
        'path' => 'sites/all/modules/custom/badcamp_images/bg-white.png',
        'dimensions' => 'background',
      ),
      'weight' => '2',
    ),
    2 => array(
      'label' => 'Crop',
      'help' => 'Cropping will remove portions of an image to make it the specified dimensions.',
      'effect callback' => 'image_crop_effect',
      'dimensions callback' => 'image_resize_dimensions',
      'form callback' => 'image_crop_form',
      'summary theme' => 'image_crop_summary',
      'module' => 'image',
      'name' => 'image_crop',
      'data' => array(
        'width' => '255',
        'height' => '255',
        'anchor' => 'center-center',
      ),
      'weight' => '3',
    ),
  );
  $styles['sponsor_small']['effects'] = array(
    0 => array(
      'label' => 'Scale',
      'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
      'effect callback' => 'image_scale_effect',
      'dimensions callback' => 'image_scale_dimensions',
      'form callback' => 'image_scale_form',
      'summary theme' => 'image_scale_summary',
      'module' => 'image',
      'name' => 'image_scale',
      'data' => array(
        'width' => '120',
        'height' => '120',
        'upscale' => 0,
      ),
      'weight' => '1',
    ),
    1 => array(
      'label' => 'Underlay (background)',
      'help' => 'Choose the file image you wish to use as an background, and position the processed image on it.',
      'effect callback' => 'canvasactions_canvas2file_image',
      'form callback' => 'canvasactions_canvas2file_form',
      'module' => 'imagecache_canvasactions',
      'name' => 'canvasactions_canvas2file',
      'data' => array(
        'xpos' => 'center',
        'ypos' => 'center',
        'alpha' => '100',
        'path' => 'sites/all/modules/custom/badcamp_images/bg-white.png',
        'dimensions' => 'background',
      ),
      'weight' => '2',
    ),
    2 => array(
      'label' => 'Crop',
      'help' => 'Cropping will remove portions of an image to make it the specified dimensions.',
      'effect callback' => 'image_crop_effect',
      'dimensions callback' => 'image_resize_dimensions',
      'form callback' => 'image_crop_form',
      'summary theme' => 'image_crop_summary',
      'module' => 'image',
      'name' => 'image_crop',
      'data' => array(
        'width' => '120',
        'height' => '120',
        'anchor' => 'center-center',
      ),
      'weight' => '3',
    ),
  );

  return $styles;
}

/**
 * Implements hook_default_image_styles_alter().
 *
 * Alter the default image styles for use on the NEW CPR site.
 */
function badcamp_images_image_styles_alter(&$styles) {
  // Check that we only affect a default style.
  if ($styles['thumbnail']['storage'] == IMAGE_STORAGE_DEFAULT) {
    // Change the size of the thumbnail image.
    $styles['thumbnail']['effects'][0]['name'] = 'image_scale_and_crop';
    $styles['thumbnail']['effects'][0]['data'] = array(
      'width' => 55,
      'height' => 55,
      'upscale' => 0,
    );
  }

  if ($styles['medium']['storage'] == IMAGE_STORAGE_DEFAULT) {
    // Change the size of the medium image.
    $styles['medium']['effects'][0]['name'] = 'image_scale_and_crop';
    $styles['medium']['effects'][0]['data'] = array(
      'width' => 412,
      'height' => 484,
      'upscale' => 0,
    );
  }
}
