<?php
/**
 * @file
 * BADCamp panels module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function badcamp_panels_ctools_plugin_api($module, $api) {
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_directory() to let the system know
 * we implement task and task_handler plugins.
 */
function badcamp_panels_ctools_plugin_directory($module, $plugin) {
  // Safety: go away if CTools is not at an appropriate version.
  if (!module_invoke('ctools', 'api_version', PANELS_REQUIRED_CTOOLS_API)) {
    return;
  }
  if ($module == 'page_manager' || $module == 'panels' || $module == 'ctools' || $module == 'stylizer') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implemens hook_entity_info_alter().
 */
function badcamp_panels_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['newbundle'] = array(
    'label' => t('Highlight'),
    'pane category' => t('Home page'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => 'icon.png',
    'admin' => array(
      'path' => 'admin/structure/panels/entity/manage/%fieldable_panels_panes_type',
      'bundle argument' => 5,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/panels/entity/manage/newbundle',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}