<?php

/**
 * @file
 * view and menu for personal schedules
 */

function badcamp_my_schedule_menu_local_tasks_alter(&$data,$router_item,$root_path) {
    if ($router_item['path'] == 'user/%') {
        // Add a tab linking to user/%/schedule
        $data['tabs'][0]['output'][] = array(
            '#theme' => 'menu_local_task',
            '#link' => array(
                'title' => t('My Schedule'),
                'href' => $router_item['tab_root_href']  . '/schedule',
                'localized_options' => array(
                    'attributes' => array(
                        'title' => t('View my personal schedule'),
                    ),
                ),
            ),
            '#active' => ($router_item['path'] == $root_path),
        );
    }
}

/**
 * Implementation of hook_views_api().
 */
function badcamp_my_schedule_views_api() {
    return array(
        'api' => 3.0,
        'path' => drupal_get_path('module', 'badcamp_my_schedule') .'/includes'
    );
}
